### ISSUE TITLE
Refresh QR code (when lost)

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#314]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Sponsor

### Change description
Physical cards get lost. As a sponsor(/requester) I would like to refresh the QR code so that my old card is "blocked" and can not be used by somebody else.

Project context: losing cards happens very often, about 10 per week.

### Planning

- [x] | Written proposal | Deadline: 05-08-2020 | Can be checked when the issue has enough written info in issue or doc
- [x] | Figma | Deadline: 07-08-2020 | Can be checked when a proposal has reached Pull request stage in Figma
- [x] | Development | Deadline: 21-08-2020 | Can be checked when deployed on develop
- [x] | Staging | Deadline: 31-08-2020 | Can be checked when deployed on staging
- [ ] | Production  | Deadline: 07-09-2020 | Can be checked when deployed on production

**Comment by maxvisser** [comment]
Now I wonder if there would be a digital alternative (mail or Me-app) if people would even bother to order a new one

**Comment by maxvisser** [comment]
Probably the plastic card button should stay and open a modal with a 'block plastic card' button or request new card which blocks the card and allows users to refresh.

**Comment by jamalv** [comment]
> Probably the plastic card button should stay and open a modal with a 'block plastic card' button or request new card which blocks the card and allows users to refresh.

Yea I like this suggestion; could approve this if it's feasible and estimate scope? If you approve, I think next step is creating a figma proposal for this functionality.

**Comment by maxvisser** [comment]
Depends on the functionality; can only estimate the scope after figma proposal. Not sure what you ask of me with the approval. (as it is a must have? should be fixed so I see no other way of approving it right?)

**Comment by jamalv** [comment]
Functionality:

- Still show plastic card button when people have a plastic card
- Give option to "order new card"
- (ask to) block the old card - old 1001xxxx code is no longer connected to QR code
- When the new card arrives, allow people to connect it

It would also be fine if you just estimate scope :)

**Comment by maartenfv** [comment]
- [ ] | Writen proposal | Deadline: 05-08-2020
- [ ] | Figma | Deadline: 07-08-2020 |
- [ ] | Development | Deadline: 21-08-2020 |
- [ ] | Staging | Deadline: 31-08-2020 |
- [ ] | Production  | Deadline: 07-09-2020 |

**Comment by jamalv** [comment]
Figma prototype: https://www.figma.com/file/tVFrDZ4QeQpC3fyTCudwBE/Block-old-cards?node-id=1%3A76

**Comment by maxvisser** [comment]
The other two options can go on the popup (assign and order). Replace card is the only function that will work when a card is already assigned to voucher.

**Comment by maxvisser** [comment]
Added a new play page in Figma;
Commented:
Would a user ever want to block a card without ordering a new card; if so; it could be better to make block a seperate function aswell.

**Comment by maartenfv** [comment]
Discussed 10-08 we hope this could go on staging next staging release 17-08.

**Comment by maxvisser** [comment]
needs an icon for blocking cards

**Comment by maxvisser** [comment]
Currently in release v0.15.0

**Comment by maxvisser** [comment]
released
